name: Release new version
on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Create a new tag
      run: |
        curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/releases \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data "{
            \"tag_name\": \"$(date +"%Y-%m")\"
            }"
