name: Release new version
on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    name: Tag
    runs-on: ubuntu-latest
    steps:
    - name: Create a new tag
      run: |
        TAG=$(date +"%Y-%m") \
        curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/git/tags \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "tag": "${{ TAG }}",
            "message": "Monthly update - ${{ TAG }}",
            "object": "HEAD",
            "type": "commit"
            }'