name: Release new version
on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create a new tag
      run: |
        curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/git/tags \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data "{
            \"tag\": \"$(date +"%Y-%m")\",
            \"message\": \"Monthly update - $(date +"%Y-%m")\",
            \"object\": \"$(git rev-parse HEAD)\",
            \"type\": \"commit\"
            }"
